// AUTO-GENERATED FROM audit manifest. DO NOT EDIT.
import { Plugin } from '@oclif/core'

import './commands/scm/erp-manufacture-find-issue-shop.js'
import './commands/scm/erp-manufacture-find-postpone-shop.js'
import './commands/scm/erp-purchase-page.js'
import './commands/scm/purchase-core-service-get.js'
import './commands/scm/erp-manufacture-batch-sku-list.js'
import './commands/scm/erp-manufacture-customer-list.js'
import './commands/scm/erp-manufacture-customer-order-list.js'
import './commands/scm/erp-manufacture-customer-task-list.js'
import './commands/scm/erp-manufacture-customer-task.js'
import './commands/scm/erp-manufacture-customer.js'
import './commands/scm/erp-manufacture-get-customer-log.js'
import './commands/scm/erp-manufacture-get-sale-names.js'
import './commands/scm/erp-manufacture-export-excel.js'
import './commands/scm/erp-manufacture-find-issue-info.js'
import './commands/scm/erp-manufacture-find-refused-issue.js'
import './commands/scm/erp-manufacture-get-issue-info-list.js'
import './commands/scm/erp-manufacture-query-sku-issue-num-list.js'
import './commands/scm/erp-manufacture-query-smt-shop-manager.js'
import './commands/scm/erp-manufacture-query-smt-shop.js'
import './commands/scm/erp-manufacture-find-db-manufacture-evaluation.js'
import './commands/scm/erp-manufacture-find-db-manufacture-extend-list.js'
import './commands/scm/erp-manufacture-find-db-manufacture-extend.js'
import './commands/scm/erp-manufacture-findpurchase.js'
import './commands/scm/erp-manufacture-find-return-list.js'
import './commands/scm/erp-manufacture-get-manufac-cooperate-product.js'
import './commands/scm/erp-manufacture-get-manufac-product-purchase-sku.js'
import './commands/scm/erp-manufacture-get-manufac-product-purchase-spu.js'
import './commands/scm/erp-manufacture-getmanufacture-level.js'
import './commands/scm/erp-manufacture-get-manufacture-purchase.js'
import './commands/scm/erp-manufacture-get-manufacture-risk-assess.js'
import './commands/scm/erp-manufacture-find-postpone-info.js'
import './commands/scm/erp-manufacture-get-manufacture-images.js'
import './commands/scm/erp-purchase-get-stutus-list.js'
import './commands/scm/erp-purchase-query-cai-niao-in-storage-order.js'
import './commands/scm/erp-purchase-spu-list.js'
import './commands/scm/erp-purchase-view-stock-descr.js'
import './commands/scm/erp-purchase-querypurchase-custom-order-list.js'
import './commands/scm/erp-purchase-get-documentary-log.js'
import './commands/scm/erp-purchase-get-order-infos.js'
import './commands/scm/erp-purchase-purchase-task-followup-export.js'
import './commands/scm/erp-purchase-get-down-order-address.js'
import './commands/scm/erp-purchase-get-purchase-task-log-list.js'
import './commands/scm/erp-purchase-get-sku-purchase-task.js'
import './commands/scm/erp-purchase-purchase-and-manufac.js'
import './commands/scm/purchase-core-service-page.js'

export default class ScmPlugin extends Plugin {
  static readonly topic = 'scm'
  static readonly description = '供应链'

  async loadCommands(): Promise<void> {
    // Commands are auto-loaded via the glob pattern in package.json
  }
}
