import { Plugin } from '@oclif/core'

import './commands/fars/erpaccount-get-ding-ding-attendance.js'
import './commands/fars/erpaccount-country.js'
import './commands/fars/erpaccount-last-logininfo.js'
import './commands/fars/erpaccount-shop.js'
import './commands/fars/erp-finance-get-cycles.js'
import './commands/fars/erp-finance-get-finance-push-task.js'
import './commands/fars/erp-finance-sku.js'
import './commands/fars/erp-finance-auth-url.js'
import './commands/fars/yyaccount-instudio-account-getstaymessage1.js'
import './commands/fars/yyaccount-getstaymessage.js'
import './commands/fars/yyfms-id-get-developer-bill-detail.js'
import './commands/fars/yyfms-id-get-sale-bill.js'
import './commands/fars/yyfms-fms-position-name.js'
import './commands/fars/erpaccount-get-manager-month.js'
import './commands/fars/erpaccount-get-over-two-days-unshipped-delivery.js'
import './commands/fars/erpaccount-get-platform-publish-info.js'
import './commands/fars/erpaccount-get-platform-shortage-rate.js'
import './commands/fars/erpaccount-get-pro-publish-cover-rate.js'
import './commands/fars/erpaccount-get-purchaseanalysis-over-seven-day.js'
import './commands/fars/erpaccount-get-sales-level-reportkf.js'
import './commands/fars/erpaccount-get-shorage-sku-info.js'
import './commands/fars/erpaccount-get-site-by-platform.js'
import './commands/fars/erpaccount-platform-pull-down.js'
import './commands/fars/erpaccount-product-managerqhlv.js'
import './commands/fars/erpaccount-purchaseanalysis-purchased-sku-detail.js'
import './commands/fars/erpaccount-purchaseanalysis-purchase-order-detail.js'
import './commands/fars/erpaccount-purchaseanalysis-sku-detail.js'
import './commands/fars/erpaccount-show-case-by-month.js'
import './commands/fars/erpaccount-urchaseanalysis-shortage-sku-detail.js'
import './commands/fars/erpaccount-lazada-coupon-list.js'
import './commands/fars/erpaccount-lazada-un-read-message-list.js'
import './commands/fars/erpaccount-find-all-logistics.js'
import './commands/fars/erpaccount-find-express-code51-all.js'
import './commands/fars/erpaccount-find-for-country.js'
import './commands/fars/erpaccount-find-for-logisticscompany.js'
import './commands/fars/erpaccount-find-line.js'
import './commands/fars/erpaccount-find-logistics-info2.js'
import './commands/fars/erpaccount-find-logistics-provider-name-all.js'
import './commands/fars/erpaccount-find-logistics.js'
import './commands/fars/erpaccount-shopee-un-read-message-list.js'
import './commands/fars/erp-finance-excel-list.js'
import './commands/fars/erp-finance-find-platform-bill.js'
import './commands/fars/erp-finance-get-platform.js'
import './commands/fars/erp-finance-get-shop-bill.js'
import './commands/fars/erp-finance-finance-account-account-list.js'
import './commands/fars/erp-finance-finance-account-move-line-list.js'
import './commands/fars/erp-finance-finance-paypal-balance-list.js'
import './commands/fars/erp-finance-get-finance-push-task-sell.js'
import './commands/fars/erp-finance-finance-res-currency-list.js'
import './commands/fars/erp-finance-finance-analytic-account.js'
import './commands/fars/erp-finance-finance-res-partner-list.js'
import './commands/fars/erp-finance-page.js'
import './commands/fars/erp-finance-list.js'
import './commands/fars/erp-finance-get-paypal-case-address.js'
import './commands/fars/erp-finance-type.js'
import './commands/fars/erp-finance-get-paypal.js'
import './commands/fars/erp-finance-get-shop-customer-serviceer.js'
import './commands/fars/erp-finance-get-shop-manager.js'
import './commands/fars/erp-finance-get-shop-paypalcase.js'
import './commands/fars/erp-finance-case-id.js'
import './commands/fars/erp-finance-paypalcase-list.js'
import './commands/fars/erp-finance-paypal-case-reason.js'
import './commands/fars/erp-finance-get-paypal-case-constant.js'
import './commands/fars/erp-fin-manage-data-erp-fin-manage-data.js'
import './commands/fars/erp-fin-manage-data-parallel-last-month-advance-infos.js'
import './commands/fars/erp-fin-manage-data-parallel-his-bill-infos-fetcher.js'
import './commands/fars/erp-fin-manage-data-parallel-info-process-fetcher.js'
import './commands/fars/erp-fin-manage-data-parallel-pay-contrast-fetcher.js'
import './commands/fars/erp-fin-manage-data-parallel-tk-bill-infos-fetcher.js'
import './commands/fars/erp-fin-manage-data-parallel-tk-query-lianlian-fetcher.js'
import './commands/fars/erp-fin-manage-data-parallel-tk-reference-provision.js'
import './commands/fars/erp-fin-manage-data-parallel-tk-voucher-provision-fetcher.js'
import './commands/fars/erp-fin-manage-data-parallel-verification-fetcher.js'
import './commands/fars/erp-fin-manage-data-query-company-id-info.js'
import './commands/fars/erp-fin-manage-data-query-download-infos-fetcher.js'
import './commands/fars/erp-fin-manage-data-query-upload-infos-fetcher.js'
import './commands/fars/erp-fin-manage-data-parallel-tk-reference-refund.js'
import './commands/fars/crm-web-service-refund-condition.js'
import './commands/fars/finance-lingxing-data-service-parallel-lingxing-download-infos.js'
import './commands/fars/yyfms-export-account-date.js'
import './commands/fars/yyfms-get-account-cost-list.js'
import './commands/fars/erp-finance-get-expense-list.js'
import './commands/fars/yyaccount-getmessage.js'

export default class FarsPlugin extends Plugin {
  static readonly topic = 'fars'
  static readonly description = '财务系统'

  async loadCommands(): Promise<void> {
    // Commands are auto-loaded via the glob pattern in package.json
  }
}
