// AUTO-GENERATED FROM audit manifest. DO NOT EDIT.
// Source: manifests/mbs-api-manifest.json
// Manifest: 2026-05-20T00:00:00+08:00 @ e4084006f47bd5ad48408ee2ec3af402e3ab27bf3853c7c78463268e0573f582
import { Flags } from '@oclif/core'
import { MBSCommand } from '@mb-it-org/shared'

export default class ProductErpMonitorHotProductAllListing extends MBSCommand {
  static description = '在线商品列表展示：按平台/店铺/组织/销量/状态等条件分页查询在线商品(热销Listing)列表。数据源为ES商品SPU索引，查询后回填删除/编辑/改价/复制/同步等任务状态、白名单标记、店铺状态、TikTok差评率、SMT实时调控等。ES scroll分页。'

  static flags = {
    platformId: Flags.integer({ description: '平台id，单选。枚举：1=eBay，2=Amazon，10=速卖通(SMT)，16=Wish，18=Lazada，26=Shopee，85=Joom，97=Walmart，108=美客多(MercadoLibre)，119=Ozon，120=TikTok，128=Temu。影响特殊逻辑：97按globalProductId匹配itemIdList并支持gmShop；108自动为itemId补MLM/MLC/MLB/MCO前缀；2/119输入itemId时先搜SKU索引汇总父ASIN；1站点二字码转全称(CA→Canada等)' }),
    shopId: Flags.string({ description: '店铺id列表，ES termsQuery(shopId)精确多选 (comma-separated)' }),
    currency: Flags.string({ description: '货币（DTO保留字段，本接口查询逻辑未使用）' }),
    shopType: Flags.string({ description: '店铺类型(非保护店铺筛选)，matchQuery(shopType)；空/不传=不过滤' }),
    minPrice: Flags.string({ description: '售价最小值。查询条件为 ES minPrice > 该值（开区间，不含等于）' }),
    maxPrice: Flags.string({ description: '售价最大值。查询条件为 ES maxPrice < 该值（开区间，不含等于）' }),
    costPriceMax: Flags.string({ description: '成本价上限（注意DTO注释把Max/Min写反，以代码为准）。查询条件为 ES maxCostPrice < 该值' }),
    costPriceMin: Flags.string({ description: '成本价下限。查询条件为 ES minCostPrice > 该值' }),
    managerShopIds: Flags.string({ description: '登录人(销售部)管理的店铺ID列表。服务端在setHotProductListShopParams中按登录人自动注入，前端无需传；销售部账号若名下无店铺直接返回code=500\'销售名下没有店铺，没有权限查看\' (comma-separated)' }),
    director: Flags.string({ description: '总监(员工ID)多选，用于按组织架构圈定店铺集合(getShopListByParams)，结果写入finalShopNameList (comma-separated)' }),
    manager: Flags.string({ description: '经理(员工ID)多选，用途同director (comma-separated)' }),
    littleLeaders: Flags.string({ description: '主管(员工ID)多选，用途同director (comma-separated)' }),
    shopManager: Flags.string({ description: '店长(员工ID)多选，用途同director (comma-separated)' }),
    shopNames: Flags.string({ description: '店铺名称多选。传入后服务端结合isopenshop/operatestatus过滤店铺运营状态，结果写入finalShopNameList；过滤后为空返回code=500\'未查询到店铺，请确认所选店铺的运营状态\' (comma-separated)' }),
    allPlatformId: Flags.string({ description: '登录人有权限的全部平台ID。服务端按登录人(销售部)自动注入；未配置平台返回code=500\'当前登录人未设置平台，请设置后再查看\'。前端无需传 (comma-separated)' }),
    finalShopNameList: Flags.string({ description: '最终生效的店铺名集合(ES termsQuery shopName)。服务端根据shopNames/组织条件/店铺状态计算注入，前端无需传 (comma-separated)' }),
    orderWay: Flags.string({ description: '排序方向。枚举：asc=升序(正序)；其他任意值或不传=降序(倒序，默认)。注意DTO注释\'DESC 升序\'有误，以代码为准' }),
    orderFiled: Flags.string({ description: '排序字段(ES字段名)。页面枚举：spuDateUploaded=发布时间，spuSevenOrdernum=7天订单量(页面默认)，spuGrossProfit=30天毛利，spuThirtyDaysSoldCount=30天销量，spuThirtyOrdernum=30天订单量，spuFiftyOneOrdernum=51天订单量，spuNinetyOrdernum=90天订单量，spuProfitRate=30天毛利率，erpSpuCreateDate=开发时间，spuWatchCount=浏览量，spuNumberSaves=收藏量，rate=评价分数；传collection会被自动转为spuNumberSaves', required: true }),
    emoloyeeId: Flags.string({ description: '员工ID(字段名拼写即如此)。本接口查询逻辑未使用' }),
    startTime: Flags.string({ description: '刊登(上传)时间起，格式yyyy-MM-dd。查询 spuDateUploaded >= 该日00:00(东八区)' }),
    endTime: Flags.string({ description: '刊登(上传)时间止，格式yyyy-MM-dd。查询 spuDateUploaded < 次日00:00(东八区，即含当天)' }),
    shopIds: Flags.string({ description: '店铺ID列表(DTO保留字段，本接口查询使用的是shopId字段) (comma-separated)' }),
    currPage: Flags.integer({ description: '当前页码，从1开始；不传默认1' }),
    matchKey: Flags.string({ description: '标题关键词搜索，逗号分隔多个词(OR短语匹配spuTitle)；服务端自动排除\'for/Für/Pour/Para/per + android/apple/google/mi/philips/samsung\'组合(禁词豁免)' }),
    sidCheck: Flags.integer({ description: '手动刊登筛选。枚举：1=只查手动刊登(mustNot autoPublish=true)；其他值/不传=不过滤' }),
    publishOper: Flags.string({ description: '刊登人账号，ES termsQuery(publishOper)精确匹配' }),
    spuDescription: Flags.string({ description: 'SPU搜索输入框原始值，逗号分隔多个SPU，最多500个(超出返回code=500\'spu不能超过500条！\')；服务端拆分后写入spuList' }),
    sku: Flags.string({ description: 'SKU搜索输入框原始值，逗号分隔，最多500个(超出返回code=500\'sku不能超过500条！\')；服务端拆分后写入skuList，并触发先查SKU索引→取父SPUId(itemIds)再查SPU索引的两段式查询' }),
    spuList: Flags.string({ description: 'SPU列表(termsQuery erpSPU)。特殊：仅1个且包含outstock/@#zdph/@#gm时改为platformSPU通配模糊查询 (comma-separated)' }),
    projectSpu: Flags.string({ description: '项目(选品项目)中的SPU列表，termsQuery(erpSPU) (comma-separated)' }),
    skuList: Flags.string({ description: 'SKU列表。非空即触发SKU索引前置查询(isneedSearchSku)；仅1个且包含outstock/@#zdph/@#gm时按platformSKU通配模糊查 (comma-separated)' }),
    logisticsType: Flags.string({ description: '物流方式，ES wildcardQuery(shippingService)模糊匹配' }),
    itemId: Flags.string({ description: '平台商品ID搜索输入框原始值，支持空格/逗号分隔多个，最多1000条(超出返回code=500\'itemid不能超过1000条！\'，白名单账号除外)；服务端拆分写入itemIdList；平台108自动补MLM/MLC/MLB/MCO前缀' }),
    yySpuStatus: Flags.integer({ description: '商品状态。枚举：-1=被拒(REJECTED)，0=下架(OFFLINE)，1=在线(ONLINE，前端默认)，2=审核中(AUDITING)，3=暂停(服务端转换为 yySpuStatus=0 且 spuStatus∈{seller_deactivated,platform_deactivated})；前端选\'4\'(全部)时不传该字段' }),
    firstCategory: Flags.string({ description: '一级分类，逗号分隔多个；服务端拆分写入categorys后termsQuery(firstCategory)，与secondCategory为OR关系' }),
    secondCategory: Flags.string({ description: '二级分类(DTO注释\'一级分类\'有误)，逗号分隔；服务端拆分写入secondCategorys后termsQuery(secondCategory)，与firstCategory为OR关系' }),
    bigChief: Flags.string({ description: '大酋长(团队最高负责人姓名)。本接口查询逻辑未直接使用(前端用saleLeader组合实现)' }),
    isSold: Flags.integer({ description: '30天有售出筛选。枚举：1=只查30天销量>0(spuThirtyDaysSoldCount>0)；其他值/不传=不过滤' }),
    site: Flags.string({ description: '站点，逗号分隔；服务端将中文国家名转二字码写入siteList；eBay(平台1)再做二字码→全称转换：CA=Canada，DE=Germany，AU=Australia，FR=France，IT=Italy' }),
    siteList: Flags.string({ description: '站点多选(termsQuery spuSiteCodeType)。一般由服务端从site拆分注入，也可直接传 (comma-separated)' }),
    proStatus: Flags.string({ description: '产品状态，ES wildcardQuery(proStatus)模糊匹配。常见取值：正常/清仓/停产/自动创建/海外仓/暂停销售' }),
    spuDispatchTimeMax: Flags.integer({ description: '备货时长(天)，matchQuery精确匹配该天数' }),
    price5: Flags.string({ description: '仓库类型ID列表(页面\'仓库类型\'多选，termsQuery price5)。ID与名称映射来自仓库类型字典表warehouseType(warehouseTypeId→warehouseTypeName)，响应中price5返回的是名称 (comma-separated)' }),
    country: Flags.string({ description: '发货地国家多选，termsQuery(country) (comma-separated)' }),
    payPalEmailAddress: Flags.string({ description: 'PayPal收款邮箱，matchQuery精确匹配' }),
    spuCreateTime1: Flags.string({ description: 'SPU开发(创建)时间起，格式yyyy-MM-dd。查询 erpSpuCreateDate >= 该日00:00(东八区)' }),
    spuCreateTime2: Flags.string({ description: 'SPU开发(创建)时间止，格式yyyy-MM-dd。查询 erpSpuCreateDate < 次日00:00(含当天)' }),
    profitMax: Flags.string({ description: '30天毛利率上限，spuProfitRate <= 该值' }),
    profitMin: Flags.string({ description: '30天毛利率下限，spuProfitRate >= 该值' }),
    isMedia: Flags.integer({ description: '视频筛选。枚举：1=只查有视频(mediaId存在且非空)；0或不传=不过滤(注意：0并不会筛选\'无视频\'，代码只处理==1)' }),
    minCollection: Flags.integer({ description: '收藏量最小值，spuNumberSaves > 该值(开区间)' }),
    maxCollection: Flags.integer({ description: '收藏量最大值，spuNumberSaves < 该值(开区间)' }),
    minPageView: Flags.integer({ description: '浏览量最小值，spuWatchCount > 该值(开区间)' }),
    maxPageView: Flags.integer({ description: '浏览量最大值，spuWatchCount < 该值(开区间)' }),
    minRate: Flags.string({ description: '评价分数最小值，rate >= 该值(闭区间)' }),
    maxRate: Flags.string({ description: '评价分数最大值，rate <= 该值(闭区间)' }),
    spuThirtyDaysSoldCount1: Flags.integer({ description: '30天销量下限，spuThirtyDaysSoldCount >= 该值' }),
    spuThirtyDaysSoldCount2: Flags.integer({ description: '30天销量上限，spuThirtyDaysSoldCount <= 该值' }),
    spuSevenOrdernum1: Flags.integer({ description: '7天订单量下限，spuSevenOrdernum >= 该值' }),
    spuSevenOrdernum2: Flags.integer({ description: '7天订单量上限，spuSevenOrdernum <= 该值' }),
    spuThirtyOrdernum1: Flags.integer({ description: '30天订单量下限，spuThirtyOrdernum >= 该值' }),
    spuThirtyOrdernum2: Flags.integer({ description: '30天订单量上限，spuThirtyOrdernum <= 该值' }),
    spuFiftyOneOrdernum1: Flags.integer({ description: '51天订单量下限，spuFiftyOneOrdernum >= 该值' }),
    spuFiftyOneOrdernum2: Flags.integer({ description: '51天订单量上限，spuFiftyOneOrdernum <= 该值' }),
    spuNinetyOrdernum1: Flags.integer({ description: '90天订单量下限，spuNinetyOrdernum >= 该值' }),
    spuNinetyOrdernum2: Flags.integer({ description: '90天订单量上限，spuNinetyOrdernum <= 该值' }),
    spuHalfYearOrdernum1: Flags.integer({ description: '180天订单量下限，spuHalfYearOrdernum >= 该值' }),
    spuHalfYearOrdernum2: Flags.integer({ description: '180天订单量上限，spuHalfYearOrdernum <= 该值' }),
    spuNumberSold1: Flags.integer({ description: '累计订单量下限，spuNumberSold >= 该值' }),
    spuNumberSold2: Flags.integer({ description: '累计订单量上限，spuNumberSold <= 该值' }),
    skuInventory1: Flags.integer({ description: 'SKU库存下限(skuInventory >= 该值)。该条件作用于SKU索引，传入即触发两段式查询(先SKU后SPU)' }),
    skuInventory2: Flags.integer({ description: 'SKU库存上限(skuInventory <= 该值)，同上作用于SKU索引' }),
    pageSize: Flags.integer({ description: '每页条数，不传或<0时默认50' }),
    isQingcang: Flags.string({ description: '清仓筛选。枚举："1"=只查清仓刊登(ES qingcang=true，清仓刊登SKU带@#QC-标记)；其他=不过滤' }),
    autoPublish: Flags.string({ description: '批量刊登筛选。枚举："1"=只查批量刊登(ES autoPublish=true)；其他=不过滤' }),
    isNotActive: Flags.integer({ description: '不活跃listing筛选(SMT平台逻辑)。枚举：1=只查不活跃listing，判定条件：SPU创建时间超89天 且 listing上架超179天 且 180天订单量<=0；其他=不过滤' }),
    statisDate: Flags.string({ description: '统计日期 yyyy-MM-dd(GMT+8)。DTO保留字段，本接口查询逻辑未使用' }),
    scrollId: Flags.string({ description: 'ES scroll分页标识。第1页不传；翻页时回传上一次响应obj.scrollId' }),
    itemIds: Flags.string({ description: '商品ID列表(termsQuery spuId)。SKU两段式查询时由服务端用SKU索引查到的父SPUId覆盖注入 (comma-separated)' }),
    itemIdList: Flags.string({ description: '商品ID列表，由服务端从itemId拆分注入。平台97(Walmart)按globalProductId匹配，其他平台按spuId匹配；平台2/119(Amazon/Ozon)时与SKU索引查得的父ASIN合并 (comma-separated)' }),
    customerService: Flags.string({ description: '客户经理多选，用于店铺圈定(getShopListByParams的SQL条件) (comma-separated)' }),
    categorys: Flags.string({ description: '一级分类列表，服务端由firstCategory逗号拆分注入，termsQuery(firstCategory) (comma-separated)' }),
    secondCategorys: Flags.string({ description: '二级分类列表，服务端由secondCategory逗号拆分注入，termsQuery(secondCategory) (comma-separated)' }),
    exportItemIds: Flags.string({ description: '页面勾选的itemId列表(导出场景用，作用于SKU索引parentSPUId)。本列表接口查询不使用 (comma-separated)' }),
    whiteList: Flags.string({ description: '不调控白名单筛选。枚举："1"=只查不调控白名单内listing(服务端按平台查白名单itemId注入whiteListItemId；白名单为空时返回code=0提示\'白名单中没有listing\'，最终响应code=200+空列表)；其他=不过滤' }),
    whiteListItemId: Flags.string({ description: '不调控白名单itemId列表(termsQuery spuId)。服务端根据whiteList=1注入，前端无需传 (comma-separated)' }),
    tortWhiteListing: Flags.string({ description: '(侵权、禁售)白名单筛选。枚举："1"=只查该白名单内listing；其他=不过滤' }),
    tortWhiteListItemId: Flags.string({ description: '(侵权、禁售)白名单ES文档_id列表(termsQuery _id)。服务端根据tortWhiteListing=1注入 (comma-separated)' }),
    infringingWhiteWord: Flags.string({ description: '(侵权词)白名单筛选。枚举："1"=只查该白名单内listing；其他=不过滤' }),
    infringingWhiteWordItem: Flags.string({ description: '(侵权词)白名单ES文档_id列表(termsQuery _id)。服务端根据infringingWhiteWord=1注入 (comma-separated)' }),
    continuouOrderFifteen: Flags.integer({ description: '连续15天出单筛选。枚举：1=只查连续15天稳定出单(ES continuouOrderFifteen=1)；其他=不过滤' }),
    continuouOrderThirty: Flags.integer({ description: '连续30天出单筛选。枚举：1=只查连续30天稳定出单(ES continuouOrderThirty=1)；其他=不过滤' }),
    tort: Flags.integer({ description: '侵权筛选。枚举：1=只查侵权listing(ES tort=1)；其他=不过滤' }),
    bannedPlatform: Flags.string({ description: '禁售平台名称列表，逗号拼接后matchQuery(bannedPlatform) (comma-separated)' }),
    sellWellCountry: Flags.string({ description: '热销国家多选，OR短语匹配(matchPhraseQuery sellWellCountry) (comma-separated)' }),
    lowRate: Flags.integer({ description: '低分listing筛选。枚举：1=只查低分listing(0 < rate <= 3)；其他=不过滤' }),
    folderId: Flags.integer({ description: '收藏夹ID。传入则只查当前登录人该收藏夹内的listing(服务端查出ES文档id注入collectProIds)；收藏夹为空返回code=0提示\'没有加入收藏的listing\'(最终响应code=200+空列表)' }),
    collectProIds: Flags.string({ description: '收藏的ES文档_id列表(termsQuery _id)。服务端根据folderId注入，前端无需传 (comma-separated)' }),
    freightTemplateIds: Flags.string({ description: 'SMT运费模板ID多选，termsQuery(freightTemplateId) (comma-separated)' }),
    hasInfringedWord: Flags.integer({ description: '是否包含侵权词。枚举：1=只查标题含侵权词(infringedWord字段存在且非空)；0(默认)=不过滤' }),
    productTagList: Flags.string({ description: '产品标签多选，OR短语匹配(matchPhraseQuery productTag) (comma-separated)' }),
    diagnosisType: Flags.integer({ description: '诊断类型(SMT商品诊断)，matchQuery精确匹配。枚举(前端文案)：1=商品竞争力低，2=缺少3:4场景图，3=缺少白底图，4=标题滥用，5=缺少APP独立详描' }),
    outOfStock: Flags.boolean({ description: '是否缺货。枚举：true=只查缺货，false=只查不缺货，不传=不过滤', allowNo: true }),
    isopenshop: Flags.string({ description: '店铺启用状态(店铺圈定条件，不进ES)。枚举："1"=已开启，"0"=已关闭，空/不传=全部' }),
    operatestatus: Flags.string({ description: '店铺运营状态(店铺圈定条件，不进ES)。枚举："1"=运营中，"2"=暂停运营，"3"=永久关闭中，空/不传=全部' }),
    smtProductType: Flags.string({ description: 'SMT商品类型，matchQuery精确匹配。枚举："0"=仓发，"1"=即时补货(JIT)，"2"=海外备仓；前端勾选\'即时补货\'时传1' }),
    specialmark: Flags.string({ description: '特殊标记，matchQuery精确匹配' }),
    threeDaySalesChange: Flags.string({ description: '销量骤跌阈值。查询 ES threeDaySalesChange <= 该值(近3天销量相对近3-6天销量的涨跌幅)。前端勾选\'销量骤跌\'固定传-0.2，即跌幅达20%以上' }),
    autoPublishType: Flags.integer({ description: '刊登类型，matchQuery精确匹配。枚举：0=其他(手动)，1=批量刊登(SKU带@#ZDSJ)，2=自动刊登(SKU带@#ZDPH)，3=复制刊登(前端CopyPublish勾选传3)' }),
    autoPublishTypeList: Flags.string({ description: '刊登类型多选，termsQuery(autoPublishType)，枚举同autoPublishType (comma-separated)' }),
    hasPhishingWord: Flags.integer({ description: '是否包含钓鱼词。枚举：1=只查含钓鱼词(phishingWord字段存在且非空)；0(默认)=不过滤' }),
    amazonFollowUp: Flags.boolean({ description: 'Amazon跟买筛选。枚举：true=只查被跟买(ES followUp=true)，false=只查未被跟买，不传=不过滤', allowNo: true }),
    groupCompanyId: Flags.integer({ description: '所属公司ID(matchQuery companyId)。服务端用登录人所属公司强制覆盖，前端传值无效' }),
    brand: Flags.string({ description: '品牌，matchQuery(brand)' }),
    multipleWarehousesLabel: Flags.string({ description: '一品多仓标签筛选(termQuery)。前端勾选传1；与multipleWarehousesTestLabel同时传时两者为OR关系(minimumShouldMatch=1)' }),
    multipleWarehousesTestLabel: Flags.string({ description: '一品多仓测品标签筛选(termQuery)。前端勾选传"1"；与multipleWarehousesLabel同时传时为OR关系' }),
    tortStartTime: Flags.string({ description: '侵权更新时间起，格式yyyy-MM-dd HH:mm:ss，查询 tortUpdateTime >= 该值' }),
    tortEndTime: Flags.string({ description: '侵权更新时间止，格式yyyy-MM-dd HH:mm:ss，查询 tortUpdateTime <= 该值' }),
    skuId: Flags.string({ description: 'SKU ID(DTO保留字段，本接口查询逻辑未使用)' }),
    gmShop: Flags.string({ description: 'GM店铺筛选(仅Walmart)。枚举："1"且platformId=97且未选店铺时，服务端自动以GM店铺清单作为shopNames；其他=不生效' }),
    ozonFbpProduct: Flags.integer({ description: 'Ozon FBP仓库筛选。枚举：1=只查FBP商品(termQuery ozonFbpProduct=1)；0=排除FBP商品(mustNot ozonFbpProduct=1)；不传=不过滤' }),
    bundType: Flags.integer({ description: '是否绑定商品。枚举：1=绑定，0=非绑定(termQuery bundType)；不传=不过滤' }),
  }

  async run(): Promise<void> {
    const { flags } = await this.parse(ProductErpMonitorHotProductAllListing)

    const toArray = (value: string | undefined, itemType = 'string'): unknown[] | undefined => {
      if (value === undefined) return undefined
      const items = value.split(',').map((item) => item.trim()).filter(Boolean)
      if (itemType === 'integer' || itemType === 'number') return items.map((item) => Number(item))
      return items
    }

    const data = await this.client.post('/erpmonitor/erpmonitor/hotProductMonitor/hotProductAllListing', { "platformId": flags.platformId, "shopId": toArray(flags.shopId, 'integer'), "currency": flags.currency, "shopType": flags.shopType, "minPrice": flags.minPrice, "maxPrice": flags.maxPrice, "costPriceMax": flags.costPriceMax, "costPriceMin": flags.costPriceMin, "managerShopIds": toArray(flags.managerShopIds, 'integer'), "director": toArray(flags.director, 'integer'), "manager": toArray(flags.manager, 'integer'), "littleLeaders": toArray(flags.littleLeaders, 'integer'), "shopManager": toArray(flags.shopManager, 'integer'), "shopNames": toArray(flags.shopNames, 'string'), "allPlatformId": toArray(flags.allPlatformId, 'string'), "finalShopNameList": toArray(flags.finalShopNameList, 'string'), "orderWay": flags.orderWay, "orderFiled": flags.orderFiled, "emoloyeeId": flags.emoloyeeId, "startTime": flags.startTime, "endTime": flags.endTime, "shopIds": toArray(flags.shopIds, 'integer'), "currPage": flags.currPage, "matchKey": flags.matchKey, "sidCheck": flags.sidCheck, "publishOper": flags.publishOper, "spuDescription": flags.spuDescription, "sku": flags.sku, "spuList": toArray(flags.spuList, 'string'), "projectSpu": toArray(flags.projectSpu, 'string'), "skuList": toArray(flags.skuList, 'string'), "logisticsType": flags.logisticsType, "itemId": flags.itemId, "yySpuStatus": flags.yySpuStatus, "firstCategory": flags.firstCategory, "secondCategory": flags.secondCategory, "bigChief": flags.bigChief, "isSold": flags.isSold, "site": flags.site, "siteList": toArray(flags.siteList, 'string'), "proStatus": flags.proStatus, "spuDispatchTimeMax": flags.spuDispatchTimeMax, "price5": toArray(flags.price5, 'string'), "country": toArray(flags.country, 'string'), "payPalEmailAddress": flags.payPalEmailAddress, "spuCreateTime1": flags.spuCreateTime1, "spuCreateTime2": flags.spuCreateTime2, "profitMax": flags.profitMax, "profitMin": flags.profitMin, "isMedia": flags.isMedia, "minCollection": flags.minCollection, "maxCollection": flags.maxCollection, "minPageView": flags.minPageView, "maxPageView": flags.maxPageView, "minRate": flags.minRate, "maxRate": flags.maxRate, "spuThirtyDaysSoldCount1": flags.spuThirtyDaysSoldCount1, "spuThirtyDaysSoldCount2": flags.spuThirtyDaysSoldCount2, "spuSevenOrdernum1": flags.spuSevenOrdernum1, "spuSevenOrdernum2": flags.spuSevenOrdernum2, "spuThirtyOrdernum1": flags.spuThirtyOrdernum1, "spuThirtyOrdernum2": flags.spuThirtyOrdernum2, "spuFiftyOneOrdernum1": flags.spuFiftyOneOrdernum1, "spuFiftyOneOrdernum2": flags.spuFiftyOneOrdernum2, "spuNinetyOrdernum1": flags.spuNinetyOrdernum1, "spuNinetyOrdernum2": flags.spuNinetyOrdernum2, "spuHalfYearOrdernum1": flags.spuHalfYearOrdernum1, "spuHalfYearOrdernum2": flags.spuHalfYearOrdernum2, "spuNumberSold1": flags.spuNumberSold1, "spuNumberSold2": flags.spuNumberSold2, "skuInventory1": flags.skuInventory1, "skuInventory2": flags.skuInventory2, "pageSize": flags.pageSize, "isQingcang": flags.isQingcang, "autoPublish": flags.autoPublish, "isNotActive": flags.isNotActive, "statisDate": flags.statisDate, "scrollId": flags.scrollId, "itemIds": toArray(flags.itemIds, 'string'), "itemIdList": toArray(flags.itemIdList, 'string'), "customerService": toArray(flags.customerService, 'string'), "categorys": toArray(flags.categorys, 'string'), "secondCategorys": toArray(flags.secondCategorys, 'string'), "exportItemIds": toArray(flags.exportItemIds, 'string'), "whiteList": flags.whiteList, "whiteListItemId": toArray(flags.whiteListItemId, 'string'), "tortWhiteListing": flags.tortWhiteListing, "tortWhiteListItemId": toArray(flags.tortWhiteListItemId, 'string'), "infringingWhiteWord": flags.infringingWhiteWord, "infringingWhiteWordItem": toArray(flags.infringingWhiteWordItem, 'string'), "continuouOrderFifteen": flags.continuouOrderFifteen, "continuouOrderThirty": flags.continuouOrderThirty, "tort": flags.tort, "bannedPlatform": toArray(flags.bannedPlatform, 'string'), "sellWellCountry": toArray(flags.sellWellCountry, 'string'), "lowRate": flags.lowRate, "folderId": flags.folderId, "collectProIds": toArray(flags.collectProIds, 'string'), "freightTemplateIds": toArray(flags.freightTemplateIds, 'integer'), "hasInfringedWord": flags.hasInfringedWord, "productTagList": toArray(flags.productTagList, 'string'), "diagnosisType": flags.diagnosisType, "outOfStock": flags.outOfStock, "isopenshop": flags.isopenshop, "operatestatus": flags.operatestatus, "smtProductType": flags.smtProductType, "specialmark": flags.specialmark, "threeDaySalesChange": flags.threeDaySalesChange, "autoPublishType": flags.autoPublishType, "autoPublishTypeList": toArray(flags.autoPublishTypeList, 'integer'), "hasPhishingWord": flags.hasPhishingWord, "amazonFollowUp": flags.amazonFollowUp, "groupCompanyId": flags.groupCompanyId, "brand": flags.brand, "multipleWarehousesLabel": flags.multipleWarehousesLabel, "multipleWarehousesTestLabel": flags.multipleWarehousesTestLabel, "tortStartTime": flags.tortStartTime, "tortEndTime": flags.tortEndTime, "skuId": flags.skuId, "gmShop": flags.gmShop, "ozonFbpProduct": flags.ozonFbpProduct, "bundType": flags.bundType })
    this.output(data)
  }
}
