import { Plugin } from '@oclif/core'

import './commands/ars/erpmonitor-get-yesterday-wish-account.js'
import './commands/ars/erpmonitor-yesterday-account-statement.js'
import './commands/ars/erpmonitor-spu.js'
import './commands/ars/erpmonitor-product-brand.js'
import './commands/ars/erpmonitor-export-default-paramtes.js'
import './commands/ars/erpmonitor-forbidden-listings-of-shop.js'
import './commands/ars/erpmonitor-not-in-shanghai-listing-of-shop.js'
import './commands/ars/erpmonitor-query-repeat-spu-title-of-shop.js'
import './commands/ars/erp-report-get-site-by-type.js'
import './commands/ars/erp-report-get-site.js'
import './commands/ars/erp-report-get-company-info.js'
import './commands/ars/erp-report-get-must-publish-ablity.js'
import './commands/ars/erpflowmonitor-get-item-data-monitor.js'
import './commands/ars/erpflowmonitor-get-shop-data-monitor.js'
import './commands/ars/erpmonitor-details.js'
import './commands/ars/erpmonitor-find-account.js'
import './commands/ars/erpmonitor-income-and-expend-details.js'
import './commands/ars/erpmonitor-loan.js'
import './commands/ars/erpmonitor-list-product-by-listing-allegro-product-publish.js'
import './commands/ars/erpmonitor-list-publish-shop.js'
import './commands/ars/erpmonitor-amazon-reviseprice-confirm-list.js'
import './commands/ars/erpmonitor-get-amazon-not-fba-shop.js'
import './commands/ars/erpmonitor-get-parent-category-name.js'
import './commands/ars/erpmonitor-ebay-reviseprice-confirm-list.js'
import './commands/ars/erpmonitor-find-shops-ebay-reviseprice-confirm.js'
import './commands/ars/erpmonitor-get-ebay-reviseprice-detail.js'
import './commands/ars/erpmonitor-ez-data.js'
import './commands/ars/erpmonitor-find-product-and-order.js'
import './commands/ars/erpmonitor-fanno-reviseprice-confirm-list.js'
import './commands/ars/erpmonitor-find-shops-by-shop-manager-fanno-reviseprice-confirm.js'
import './commands/ars/erpmonitor-find-shops-fanno-reviseprice-confirm.js'
import './commands/ars/erpmonitor-batch-add-revise-white-list.js'
import './commands/ars/erpmonitor-collect-folder-list.js'
import './commands/ars/erpmonitor-currency.js'
import './commands/ars/erpmonitor-details-activate-info.js'
import './commands/ars/erpmonitor-details-disabled-info.js'
import './commands/ars/erpmonitor-details-refresh-info.js'
import './commands/ars/erpmonitor-exprot-asyn-excel.js'
import './commands/ars/erpmonitor-get-all-emp-name.js'
import './commands/ars/erpmonitor-get-country-from-es.js'
import './commands/ars/erpmonitor-get-inventory-log.js'
import './commands/ars/erpmonitor-get-listing-log.js'
import './commands/ars/erpmonitor-get-publish-oper-list.js'
import './commands/ars/erpmonitor-get-shop-freight-templates.js'
import './commands/ars/erpmonitor-get-site-by-platform.js'
import './commands/ars/erpmonitor-hot-product-with-shop.js'
import './commands/ars/erpmonitor-hot-product-with-sku.js'
import './commands/ars/erpmonitor-platform.js'
import './commands/ars/erpmonitor-shop-by-platform3.js'
import './commands/ars/erpmonitor-shop-by-platform.js'
import './commands/ars/erpmonitor-find-shops-by-shop-manager-lazada-reviseprice-confirm.js'
import './commands/ars/erpmonitor-find-shops-lazada-reviseprice-confirm.js'
import './commands/ars/erpmonitor-lazada-reviseprice-confirm-list.js'
import './commands/ars/erpmonitor-all-listing-spu.js'
import './commands/ars/erpmonitor-all-listing.js'
import './commands/ars/erpmonitor-hot-listing.js'
import './commands/ars/erpmonitor-getlogin-info.js'
import './commands/ars/erpmonitor-get-platform-name-and-id.js'
import './commands/ars/erpmonitor-get-publish-params-limit.js'
import './commands/ars/erpmonitor-get-shop-name-by-platform-id.js'
import './commands/ars/erpmonitor-get-shop-name.js'
import './commands/ars/erpmonitor-get-sku-online-product.js'
import './commands/ars/erpmonitor-great-chief.js'
import './commands/ars/erpmonitor-list-repeate-details.js'
import './commands/ars/erpmonitor-on-sold-product.js'
import './commands/ars/erpmonitor-product-relevant-information.js'
import './commands/ars/erpmonitor-query-forbid-publish-listing.js'
import './commands/ars/erpmonitor-sale-details.js'
import './commands/ars/erpmonitor-sku-deficit-of-shop.js'
import './commands/ars/erpmonitor-find-editor-shop.js'
import './commands/ars/erpmonitor-match-manage-shop.js'
import './commands/ars/erpmonitor-match-skus-of-shop.js'
import './commands/ars/erpmonitor-deleteshopee-reviseprice-confirm-list.js'
import './commands/ars/erpmonitor-get-discount-info-by-shop-shopee-reviseprice-confirm.js'
import './commands/ars/erpmonitor-get-item-ids-by-discount-id-shopee-reviseprice-confirm.js'
import './commands/ars/erpmonitor-pull-discount-info-of-shop-shopee-reviseprice-confirm.js'
import './commands/ars/erpmonitor-shopee-reviseprice-confirm-list.js'
import './commands/ars/erpmonitor-list-product-by-listing-shopify-convent-sku.js'
import './commands/ars/erpmonitor-shopify-detail-csv.js'
import './commands/ars/erpmonitor-get-customer-service-leader.js'
import './commands/ars/erpmonitor-get-customer-service-shop.js'
import './commands/ars/erpmonitor-get-customer-service.js'
import './commands/ars/erpmonitor-find-shops-tiktok-reviseprice-confirm.js'
import './commands/ars/erpmonitor-get-discount-info-by-shop-tiktok-reviseprice-confirm.js'
import './commands/ars/erpmonitor-get-item-ids-by-discount-id-tiktok-reviseprice-confirm.js'
import './commands/ars/erpmonitor-get-submit-info.js'
import './commands/ars/erpmonitor-pull-discount-info-of-shop-tiktok-reviseprice-confirm.js'
import './commands/ars/erpmonitor-site-list.js'
import './commands/ars/erpmonitor-tiktok-reviseprice-confirm-list.js'
import './commands/ars/erp-report-get-aliexpress-pop-product.js'
import './commands/ars/erp-report-list-balance.js'
import './commands/ars/erp-report-list-daily-sale-fee.js'
import './commands/ars/erp-report-get-db-spu-sales-status-shop-data-details.js'
import './commands/ars/erp-report-get-db-spu-sales-status-shop-datas.js'
import './commands/ars/erp-report-get-db-sales-points-details.js'
import './commands/ars/erp-report-get-db-sales-points.js'
import './commands/ars/erp-report-get-kf-db-sales-points-details.js'
import './commands/ars/erp-report-get-kf-db-sales-points.js'
import './commands/ars/erp-report-download-supplier.js'
import './commands/ars/erp-report-get-supplier-primary.js'
import './commands/ars/erp-report-list-report.js'
import './commands/ars/erp-report-download.js'
import './commands/ars/erp-report-get-today-push-shuo-ming-shu.js'
import './commands/ars/erp-report-get-today-push-team.js'
import './commands/ars/erp-report-query-import-history.js'

export default class ArsPlugin extends Plugin {
  static readonly topic = 'ars'
  static readonly description = '数据分析与报表'

  async loadCommands(): Promise<void> {
    // Commands are auto-loaded via the glob pattern in package.json
  }
}
