// AUTO-GENERATED FROM audit manifest. DO NOT EDIT.
import { Plugin } from '@oclif/core'

import './commands/prm/erpsoldout-get-all-site.js'
import './commands/prm/erpsoldout-id-get-pantent-country-by-id1.js'
import './commands/prm/erpsoldout-id-get-pantent-country-by-id.js'
import './commands/prm/erpsoldout-get-pantent-country.js'
import './commands/prm/erpsoldout-get-site.js'
import './commands/prm/product-auto-listing-service-platform-type-enum.js'
import './commands/prm/yypms-shop-name.js'
import './commands/prm/yypms-spu.js'
import './commands/prm/yypms-id-get-developer-approval-by-id.js'
import './commands/prm/yypms-sequenceid.js'
import './commands/prm/yypms-id-get-condition-required-info-v3.js'
import './commands/prm/yypms-pms-id.js'
import './commands/prm/erp-publish-get-small-shop-by-big-shop.js'
import './commands/prm/erp-publish-list-have-published-shop-joom-product-publish.js'
import './commands/prm/erp-publish-list-product-by-listing-joom-product-publish.js'
import './commands/prm/erp-publish-list-un-publish-shop.js'
import './commands/prm/erp-publish-forbid-sku-list.js'
import './commands/prm/erp-publish-get-publish-detail-info.js'
import './commands/prm/erp-publish-list-have-published-shop-product-publish.js'
import './commands/prm/erp-publish-list-product-by-listing-product-publish.js'
import './commands/prm/erp-publish-list-publish-shop-product-publish.js'
import './commands/prm/erp-publish-find-publish-detail-by-shopname-shopee-product-controller.js'
import './commands/prm/erp-publish-find-publish-shop-shopee-product-controller.js'
import './commands/prm/erp-publish-find-shopee-autopublish-spu.js'
import './commands/prm/erp-publish-list-publish-shop-smt-product-publish.js'
import './commands/prm/erp-publish-list-relisting-details.js'
import './commands/prm/erp-publish-list-relisting-results.js'
import './commands/prm/erp-publish-get-price-channel-by-site.js'
import './commands/prm/erp-publish-find-publish-detail-by-shopname-tiktok-product-controller.js'
import './commands/prm/erp-publish-find-publish-shop-tiktok-product-controller.js'
import './commands/prm/erp-publish-find-shop-param-by-shopname.js'
import './commands/prm/erp-publish-find-tiktok-autopublish-spu.js'
import './commands/prm/erp-publish-fin-tiktok-first-category.js'
import './commands/prm/erpsoldout-befor-verifier-infringing.js'
import './commands/prm/erpsoldout-category.js'
import './commands/prm/erpsoldout-check-is-batch.js'
import './commands/prm/erpsoldout-emp-id.js'
import './commands/prm/erpsoldout-find-creater-infringing.js'
import './commands/prm/erpsoldout-findinfringing.js'
import './commands/prm/erpsoldout-find-infring-num.js'
import './commands/prm/erpsoldout-find-infring-product-num.js'
import './commands/prm/erpsoldout-find-platform-infringing.js'
import './commands/prm/erpsoldout-find-shop.js'
import './commands/prm/erpsoldout-get-examine-team-authority.js'
import './commands/prm/erpsoldout-get-info-submit.js'
import './commands/prm/erpsoldout-get-infringing-sku-info.js'
import './commands/prm/erpsoldout-get-pms-infringed-words.js'
import './commands/prm/erpsoldout-get-pms-phishing-words-list.js'
import './commands/prm/erpsoldout-get-pms-phishing-words-log-list.js'
import './commands/prm/erpsoldout-get-pms-phishing-words.js'
import './commands/prm/erpsoldout-on-line-product-infringing.js'
import './commands/prm/erpsoldout-sould-out-sku-list.js'
import './commands/prm/erpsoldout-submit.js'
import './commands/prm/erpsoldout-info.js'
import './commands/prm/erpsoldout-verifier.js'
import './commands/prm/erpsoldout-befor-verifier-sold-out.js'
import './commands/prm/erpsoldout-find-creater-sold-out.js'
import './commands/prm/erpsoldout-find-phishing-words-creater.js'
import './commands/prm/erpsoldout-find-platform-of-add.js'
import './commands/prm/erpsoldout-find-platform-sold-out.js'
import './commands/prm/erpsoldout-find-sold-out-num.js'
import './commands/prm/erpsoldout-find-sold-out-product-num.js'
import './commands/prm/erpsoldout-find-sold-out-reason.js'
import './commands/prm/erpsoldout-find-sold-out-task.js'
import './commands/prm/erpsoldout-find-sold-out-verifier.js'
import './commands/prm/erpsoldout-on-line-product-sold-out.js'
import './commands/prm/product-auto-listing-service-get-listing-template-page.js'
import './commands/prm/yypms-spu-name.js'
import './commands/prm/pms-id.js'

export default class PrmPlugin extends Plugin {
  static readonly topic = 'prm'
  static readonly description = '负责将商品信息上传到指定平台'

  async loadCommands(): Promise<void> {
    // Commands are auto-loaded via the glob pattern in package.json
  }
}
